# Generated by Django 3.2.6 on 2021-09-05 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210905_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('French', 'French'), ('Germany', 'Germany'), ('Chinese', 'Chinese'), ('Japanese', 'Japanese'), ('Spanish', 'Spanish'), ('Russian', 'Russian')], default='English', help_text="Select the book's natural language (e.g. Eglish, French, Japanese etc.)", max_length=64),
        ),
    ]
